services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: miniprogram_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: miniprogram_manager
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  # 简单的后端服务（使用通用Python镜像）
  backend-simple:
    image: python:3.11-slim
    container_name: miniprogram_backend_simple
    working_dir: /app
    environment:
      DATABASE_URL: mysql+pymysql://app_user:app_password@mysql:3306/miniprogram_manager
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
    command: |
      bash -c "
        pip install fastapi uvicorn sqlalchemy pymysql python-dotenv &&
        python main.py
      "
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local 